keys:
  - &server_aegis age16ewyt5mhydqz9eadx5m6kctdkdl8jj2yynpt8k8f0n6qnctqye5qqrym48
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_aegis
