# Declarative KDE Plasma 6 configuration via plasma-manager.
# Panel/wallpaper config is hand-authored; everything else was generated by:
#   nix run github:nix-community/plasma-manager
#
# MACHINE-SPECIFIC NOTES (aegis):
# - Desktop containment IDs (1, 26) in the configFile wallpaper section are
#   stable on this machine but will differ on a fresh bootstrap. After first
#   boot on a new machine, re-run rc2nix and update those IDs.
# - Disk sensor UUIDs in the diskusage widget are specific to aegis hardware.
# - kwinrc tiling UUIDs are also machine-specific.
{
  config,
  pkgs,
  lib,
  ...
}:
{
  programs.plasma = {
    enable = true;

    workspace = {
      # Primary screen wallpaper; per-screen overrides are in configFile below.
      wallpaper = "/run/current-system/sw/share/wallpapers/Flow";
    };

    panels = [
      {
        location = "bottom";
        floating = false;
        widgets = [
          "org.kde.plasma.kickoff"
          "org.kde.plasma.pager"
          "org.kde.plasma.marginsseparator"
          {
            name = "org.kde.plasma.icontasks";
            config.General.launchers = "applications:systemsettings.desktop,preferred://filemanager,preferred://browser,applications:com.mitchellh.ghostty.desktop";
          }
          "org.kde.plasma.marginsseparator"
          {
            name = "org.kde.plasma.systemmonitor.net";
            config = {
              Appearance.chartFace = "org.kde.ksysguard.linechart";
              Appearance.title = "Network Speed";
              Sensors.highPrioritySensorIds = ''["network/all/download","network/all/upload"]'';
              SensorColors."network/all/download" = "110,89,145";
              SensorColors."network/all/upload" = "124,145,89";
            };
          }
          {
            name = "org.kde.plasma.systemmonitor";
            config = {
              Appearance.chartFace = "org.kde.ksysguard.piechart";
              Appearance.title = "Memory Usage";
              Sensors.highPrioritySensorIds = ''["memory/physical/used"]'';
              Sensors.lowPrioritySensorIds = ''["memory/physical/total"]'';
              Sensors.totalSensors = ''["memory/physical/usedPercent"]'';
              SensorColors."memory/physical/used" = "110,89,145";
            };
          }
          {
            name = "org.kde.plasma.systemmonitor.cpu";
            config = {
              Appearance.chartFace = "org.kde.ksysguard.piechart";
              Appearance.title = "Total CPU Use";
              Sensors.highPrioritySensorIds = ''["cpu/all/usage"]'';
              Sensors.lowPrioritySensorIds = ''["cpu/all/cpuCount","cpu/all/coreCount"]'';
              Sensors.totalSensors = ''["cpu/all/usage"]'';
              SensorColors."cpu/all/usage" = "110,89,145";
            };
          }
          {
            name = "org.kde.plasma.systemmonitor.diskactivity";
            config = {
              Appearance.chartFace = "org.kde.ksysguard.linechart";
              Appearance.title = "Hard Disk Activity";
              Sensors.highPrioritySensorIds = ''["disk/all/write","disk/all/read"]'';
              SensorColors."disk/all/read" = "124,145,89";
              SensorColors."disk/all/write" = "110,89,145";
            };
          }
          {
            name = "org.kde.plasma.systemmonitor.diskusage";
            config = {
              Appearance.chartFace = "org.kde.ksysguard.horizontalbars";
              Appearance.title = "Disk Usage";
              Sensors.highPrioritySensorIds = ''["disk/.*/usedPercent"]'';
              Sensors.lowPrioritySensorIds = ''["disk/all/total"]'';
              Sensors.totalSensors = ''["disk/all/usedPercent"]'';
              # Disk UUIDs below are specific to aegis hardware — update for other machines
              SensorColors."disk/.*/usedPercent" = "110,89,145";
              SensorColors."disk/08e228dc-d61a-4125-9e6c-a17d99f2cb59/usedPercent" = "89,135,145";
              SensorColors."disk/4e16ab52-cdcb-4b3c-9882-ff0016802222/usedPercent" = "145,89,113";
              SensorColors."disk/72d06148d061141f/usedPercent" = "145,132,89";
              SensorColors."disk/all/usedPercent" = "90,145,89";
              SensorColors."disk/e85ea1b3-2c75-4985-ae87-3f2783b2bf28/usedPercent" = "145,89,113";
              SensorColors."disk/sdd/usedPercent" = "110,89,145";
            };
          }
          "org.kde.plasma.colorpicker"
          "org.kde.plasma.calendar"
          "org.kde.plasma.calculator"
          "org.kde.kdeconnect"
          {
            name = "org.kde.plasma.systemtray";
            config.General = {
              extraItems = "org.kde.plasma.clipboard,org.kde.plasma.cameraindicator,org.kde.plasma.manage-inputmethod,org.kde.plasma.keyboardlayout,org.kde.kdeconnect,org.kde.plasma.devicenotifier,org.kde.plasma.notifications,org.kde.plasma.mediacontroller,org.kde.plasma.battery,org.kde.plasma.networkmanagement,org.kde.plasma.brightness,org.kde.plasma.volume,org.kde.plasma.keyboardindicator,org.kde.kscreen,org.kde.plasma.weather,org.kde.plasma.printmanager";
              knownItems = "org.kde.plasma.clipboard,org.kde.plasma.cameraindicator,org.kde.plasma.manage-inputmethod,org.kde.plasma.keyboardlayout,org.kde.kdeconnect,org.kde.plasma.devicenotifier,org.kde.plasma.notifications,org.kde.plasma.mediacontroller,org.kde.plasma.battery,org.kde.plasma.networkmanagement,org.kde.plasma.brightness,org.kde.plasma.volume,org.kde.plasma.keyboardindicator,org.kde.kscreen,org.kde.plasma.weather,org.kde.plasma.printmanager";
            };
          }
          "org.kde.plasma.digitalclock"
          "org.kde.plasma.minimizeall"
        ];
      }
    ];

    shortcuts = {
      ActivityManager.switch-to-activity-1029b19e-aca0-4e88-8cb1-476e1816f6e7 = [ ];
      "KDE Keyboard Layout Switcher"."Switch to Last-Used Keyboard Layout" = "Meta+Alt+L";
      "KDE Keyboard Layout Switcher"."Switch to Next Keyboard Layout" = "Meta+Alt+K";
      "com.google.Chrome"."638E59A1074C433398F545E4DF64259E-toggle-side-panel" = [ ];
      kaccess."Toggle Screen Reader On and Off" = "Meta+Alt+S";
      kmix.decrease_microphone_volume = "Microphone Volume Down";
      kmix.decrease_volume = "Volume Down";
      kmix.decrease_volume_small = "Shift+Volume Down";
      kmix.increase_microphone_volume = "Microphone Volume Up";
      kmix.increase_volume = "Volume Up";
      kmix.increase_volume_small = "Shift+Volume Up";
      kmix.mic_mute = [
        "Microphone Mute"
        "Meta+Volume Mute"
      ];
      kmix.mute = "Volume Mute";
      ksmserver."Halt Without Confirmation" = [ ];
      ksmserver."Lock Session" = [
        "Meta+L"
        "Screensaver"
      ];
      ksmserver."Log Out" = "Ctrl+Alt+Del";
      ksmserver."Log Out Without Confirmation" = [ ];
      ksmserver.LogOut = [ ];
      ksmserver.Reboot = [ ];
      ksmserver."Reboot Without Confirmation" = [ ];
      ksmserver."Shut Down" = [ ];
      kwin."Activate Window Demanding Attention" = "Meta+Ctrl+A";
      kwin."Cycle Overview" = [ ];
      kwin."Cycle Overview Opposite" = [ ];
      kwin."Decrease Opacity" = [ ];
      kwin."Edit Tiles" = "Meta+T";
      kwin.Expose = "Ctrl+F9";
      kwin.ExposeAll = [
        "Ctrl+F10"
        "Launch (C)"
      ];
      kwin.ExposeClass = "Ctrl+F7";
      kwin.ExposeClassCurrentDesktop = [ ];
      kwin."Grid View" = "Meta+G";
      kwin."Increase Opacity" = [ ];
      kwin."Kill Window" = "Meta+Ctrl+Esc";
      kwin."Move Tablet to Next Output" = [ ];
      kwin.MoveMouseToCenter = "Meta+F6";
      kwin.MoveMouseToFocus = "Meta+F5";
      kwin.MoveZoomDown = [ ];
      kwin.MoveZoomLeft = [ ];
      kwin.MoveZoomRight = [ ];
      kwin.MoveZoomUp = [ ];
      kwin.Overview = "Meta+W";
      kwin."Setup Window Shortcut" = [ ];
      kwin."Show Desktop" = "Meta+D";
      kwin."Switch One Desktop Down" = "Meta+Ctrl+Down";
      kwin."Switch One Desktop Up" = "Meta+Ctrl+Up";
      kwin."Switch One Desktop to the Left" = "Meta+Ctrl+Left";
      kwin."Switch One Desktop to the Right" = "Meta+Ctrl+Right";
      kwin."Switch Window Down" = "Meta+Alt+Down";
      kwin."Switch Window Left" = "Meta+Alt+Left";
      kwin."Switch Window Right" = "Meta+Alt+Right";
      kwin."Switch Window Up" = "Meta+Alt+Up";
      kwin."Switch to Desktop 1" = "Ctrl+F1";
      kwin."Switch to Desktop 2" = "Ctrl+F2";
      kwin."Switch to Desktop 3" = "Ctrl+F3";
      kwin."Switch to Desktop 4" = "Ctrl+F4";
      kwin."Switch to Desktop 5" = [ ];
      kwin."Switch to Desktop 6" = [ ];
      kwin."Switch to Desktop 7" = [ ];
      kwin."Switch to Desktop 8" = [ ];
      kwin."Switch to Desktop 9" = [ ];
      kwin."Switch to Desktop 10" = [ ];
      kwin."Switch to Desktop 11" = [ ];
      kwin."Switch to Desktop 12" = [ ];
      kwin."Switch to Desktop 13" = [ ];
      kwin."Switch to Desktop 14" = [ ];
      kwin."Switch to Desktop 15" = [ ];
      kwin."Switch to Desktop 16" = [ ];
      kwin."Switch to Desktop 17" = [ ];
      kwin."Switch to Desktop 18" = [ ];
      kwin."Switch to Desktop 19" = [ ];
      kwin."Switch to Desktop 20" = [ ];
      kwin."Switch to Next Desktop" = [ ];
      kwin."Switch to Next Screen" = [ ];
      kwin."Switch to Previous Desktop" = [ ];
      kwin."Switch to Previous Screen" = [ ];
      kwin."Switch to Screen 0" = [ ];
      kwin."Switch to Screen 1" = [ ];
      kwin."Switch to Screen 2" = [ ];
      kwin."Switch to Screen 3" = [ ];
      kwin."Switch to Screen 4" = [ ];
      kwin."Switch to Screen 5" = [ ];
      kwin."Switch to Screen 6" = [ ];
      kwin."Switch to Screen 7" = [ ];
      kwin."Switch to Screen Above" = [ ];
      kwin."Switch to Screen Below" = [ ];
      kwin."Switch to Screen to the Left" = [ ];
      kwin."Switch to Screen to the Right" = [ ];
      kwin."Toggle Night Color" = [ ];
      kwin."Toggle Window Raise/Lower" = [ ];
      kwin."Walk Through Windows" = "Alt+Tab";
      kwin."Walk Through Windows (Reverse)" = "Alt+Shift+Tab";
      kwin."Walk Through Windows Alternative" = [ ];
      kwin."Walk Through Windows Alternative (Reverse)" = [ ];
      kwin."Walk Through Windows of Current Application" = "Alt+`";
      kwin."Walk Through Windows of Current Application (Reverse)" = "Alt+~";
      kwin."Walk Through Windows of Current Application Alternative" = [ ];
      kwin."Walk Through Windows of Current Application Alternative (Reverse)" = [ ];
      kwin."Window Above Other Windows" = [ ];
      kwin."Window Below Other Windows" = [ ];
      kwin."Window Close" = "Alt+F4";
      kwin."Window Custom Quick Tile Bottom" = [ ];
      kwin."Window Custom Quick Tile Left" = [ ];
      kwin."Window Custom Quick Tile Right" = [ ];
      kwin."Window Custom Quick Tile Top" = [ ];
      kwin."Window Fullscreen" = [ ];
      kwin."Window Grow Horizontal" = [ ];
      kwin."Window Grow Vertical" = [ ];
      kwin."Window Lower" = [ ];
      kwin."Window Maximize" = "Meta+PgUp";
      kwin."Window Maximize Horizontal" = [ ];
      kwin."Window Maximize Vertical" = [ ];
      kwin."Window Minimize" = "Meta+PgDown";
      kwin."Window Move" = [ ];
      kwin."Window Move Center" = [ ];
      kwin."Window No Border" = [ ];
      kwin."Window On All Desktops" = [ ];
      kwin."Window One Desktop Down" = "Meta+Ctrl+Shift+Down";
      kwin."Window One Desktop Up" = "Meta+Ctrl+Shift+Up";
      kwin."Window One Desktop to the Left" = "Meta+Ctrl+Shift+Left";
      kwin."Window One Desktop to the Right" = "Meta+Ctrl+Shift+Right";
      kwin."Window One Screen Down" = [ ];
      kwin."Window One Screen Up" = [ ];
      kwin."Window One Screen to the Left" = [ ];
      kwin."Window One Screen to the Right" = [ ];
      kwin."Window Operations Menu" = "Alt+F3";
      kwin."Window Pack Down" = [ ];
      kwin."Window Pack Left" = [ ];
      kwin."Window Pack Right" = [ ];
      kwin."Window Pack Up" = [ ];
      kwin."Window Quick Tile Bottom" = "Meta+Down";
      kwin."Window Quick Tile Bottom Left" = [ ];
      kwin."Window Quick Tile Bottom Right" = [ ];
      kwin."Window Quick Tile Left" = "Meta+Left";
      kwin."Window Quick Tile Right" = "Meta+Right";
      kwin."Window Quick Tile Top" = "Meta+Up";
      kwin."Window Quick Tile Top Left" = [ ];
      kwin."Window Quick Tile Top Right" = [ ];
      kwin."Window Raise" = [ ];
      kwin."Window Resize" = [ ];
      kwin."Window Shade" = [ ];
      kwin."Window Shrink Horizontal" = [ ];
      kwin."Window Shrink Vertical" = [ ];
      kwin."Window to Desktop 1" = [ ];
      kwin."Window to Desktop 2" = [ ];
      kwin."Window to Desktop 3" = [ ];
      kwin."Window to Desktop 4" = [ ];
      kwin."Window to Desktop 5" = [ ];
      kwin."Window to Desktop 6" = [ ];
      kwin."Window to Desktop 7" = [ ];
      kwin."Window to Desktop 8" = [ ];
      kwin."Window to Desktop 9" = [ ];
      kwin."Window to Desktop 10" = [ ];
      kwin."Window to Desktop 11" = [ ];
      kwin."Window to Desktop 12" = [ ];
      kwin."Window to Desktop 13" = [ ];
      kwin."Window to Desktop 14" = [ ];
      kwin."Window to Desktop 15" = [ ];
      kwin."Window to Desktop 16" = [ ];
      kwin."Window to Desktop 17" = [ ];
      kwin."Window to Desktop 18" = [ ];
      kwin."Window to Desktop 19" = [ ];
      kwin."Window to Desktop 20" = [ ];
      kwin."Window to Next Desktop" = [ ];
      kwin."Window to Next Screen" = "Meta+Shift+Right";
      kwin."Window to Previous Desktop" = [ ];
      kwin."Window to Previous Screen" = "Meta+Shift+Left";
      kwin."Window to Screen 0" = [ ];
      kwin."Window to Screen 1" = [ ];
      kwin."Window to Screen 2" = [ ];
      kwin."Window to Screen 3" = [ ];
      kwin."Window to Screen 4" = [ ];
      kwin."Window to Screen 5" = [ ];
      kwin."Window to Screen 6" = [ ];
      kwin."Window to Screen 7" = [ ];
      kwin.disableInputCapture = "Meta+Shift+Esc";
      kwin.view_actual_size = "Meta+0";
      kwin.view_zoom_in = [
        "Meta++"
        "Meta+="
      ];
      kwin.view_zoom_out = "Meta+-";
      mediacontrol.mediavolumedown = [ ];
      mediacontrol.mediavolumeup = [ ];
      mediacontrol.nextmedia = "Media Next";
      mediacontrol.pausemedia = "Media Pause";
      mediacontrol.playmedia = [ ];
      mediacontrol.playpausemedia = "Media Play";
      mediacontrol.previousmedia = "Media Previous";
      mediacontrol.stopmedia = "Media Stop";
      "org.chromium.Chromium"."9F9E405A305533467E6A6825C62C7ECD-" = [ ];
      "org.chromium.Chromium"."AF9FD02DE209EA37ECD8225AD65820B7-Ctrl+Shift+Space" = [ ];
      org_kde_powerdevil."Decrease Keyboard Brightness" = "Keyboard Brightness Down";
      org_kde_powerdevil."Decrease Screen Brightness" = "Monitor Brightness Down";
      org_kde_powerdevil."Decrease Screen Brightness Small" = "Shift+Monitor Brightness Down";
      org_kde_powerdevil.Hibernate = "Hibernate";
      org_kde_powerdevil."Increase Keyboard Brightness" = "Keyboard Brightness Up";
      org_kde_powerdevil."Increase Screen Brightness" = "Monitor Brightness Up";
      org_kde_powerdevil."Increase Screen Brightness Small" = "Shift+Monitor Brightness Up";
      org_kde_powerdevil.PowerDown = "Power Down";
      org_kde_powerdevil.PowerOff = "Power Off";
      org_kde_powerdevil.Sleep = "Sleep";
      org_kde_powerdevil."Toggle Keyboard Backlight" = "Keyboard Light On/Off";
      org_kde_powerdevil."Turn Off Screen" = [ ];
      org_kde_powerdevil.powerProfile = [
        "Battery"
        "Meta+B"
      ];
      plasmashell."Slideshow Wallpaper Next Image" = [ ];
      plasmashell."activate application launcher" = [
        "Meta"
        "Alt+F1"
      ];
      plasmashell."activate task manager entry 1" = "Meta+1";
      plasmashell."activate task manager entry 2" = "Meta+2";
      plasmashell."activate task manager entry 3" = "Meta+3";
      plasmashell."activate task manager entry 4" = "Meta+4";
      plasmashell."activate task manager entry 5" = "Meta+5";
      plasmashell."activate task manager entry 6" = "Meta+6";
      plasmashell."activate task manager entry 7" = "Meta+7";
      plasmashell."activate task manager entry 8" = "Meta+8";
      plasmashell."activate task manager entry 9" = "Meta+9";
      plasmashell."activate task manager entry 10" = [ ];
      plasmashell.clear-history = [ ];
      plasmashell.clipboard_action = "Meta+Ctrl+X";
      plasmashell.cycle-panels = "Meta+Alt+P";
      plasmashell.cycleNextAction = [ ];
      plasmashell.cyclePrevAction = [ ];
      plasmashell.edit_clipboard = [ ];
      plasmashell."manage activities" = "Meta+Q";
      plasmashell."next activity" = "Meta+A";
      plasmashell."previous activity" = "Meta+Shift+A";
      plasmashell.repeat_action = [ ];
      plasmashell."show dashboard" = "Ctrl+F12";
      plasmashell.show-barcode = [ ];
      plasmashell.show-on-mouse-pos = "Meta+V";
      plasmashell."stop current activity" = "Meta+S";
      plasmashell."switch to next activity" = [ ];
      plasmashell."switch to previous activity" = [ ];
      plasmashell."toggle do not disturb" = [ ];
      "services/com.mitchellh.ghostty.desktop"._launch = [ ];
      "services/org.kde.krunner.desktop"._launch = [
        "Meta+Space"
        "Alt+F2"
        "Alt+Space"
        "Search"
      ];
    };

    configFile = {
      # --- Wallpapers (stable symlink paths, safe across GC) ---
      # Desktop containment IDs are stable on aegis; re-run rc2nix on new machines.
      "plasma-org.kde.plasma.desktop-appletsrc"."Containments/1/Wallpaper/org.kde.image/General" = {
        Image = "/run/current-system/sw/share/wallpapers/Flow/";
        SlidePaths = "/run/current-system/sw/share/wallpapers/";
      };
      "plasma-org.kde.plasma.desktop-appletsrc"."Containments/26/Wallpaper/org.kde.image/General" = {
        Image = "/run/current-system/sw/share/wallpapers/Kay/";
        SlidePaths = "/run/current-system/sw/share/wallpapers/";
      };

      # --- Baloo (file indexer) ---
      baloofilerc.General.dbVersion = 2;
      baloofilerc.General."exclude filters" =
        "*~,*.part,*.o,*.la,*.lo,*.loT,*.moc,moc_*.cpp,qrc_*.cpp,ui_*.h,cmake_install.cmake,CMakeCache.txt,CTestTestfile.cmake,libtool,config.status,confdefs.h,autom4te,conftest,confstat,Makefile.am,*.gcode,.ninja_deps,.ninja_log,build.ninja,*.csproj,*.m4,*.rej,*.gmo,*.pc,*.omf,*.aux,*.tmp,*.po,*.vm*,*.nvram,*.rcore,*.swp,*.swap,lzo,litmain.sh,*.orig,.histfile.*,.xsession-errors*,*.map,*.so,*.a,*.db,*.qrc,*.ini,*.init,*.img,*.vdi,*.vbox*,vbox.log,*.qcow2,*.vmdk,*.vhd,*.vhdx,*.sql,*.sql.gz,*.ytdl,*.tfstate*,*.class,*.pyc,*.pyo,*.elc,*.qmlc,*.jsc,*.fastq,*.fq,*.gb,*.fasta,*.fna,*.gbff,*.faa,po,CVS,.svn,.git,_darcs,.bzr,.hg,CMakeFiles,CMakeTmp,CMakeTmpQmake,.moc,.obj,.pch,.uic,.npm,.yarn,.yarn-cache,__pycache__,node_modules,node_packages,nbproject,.terraform,.venv,venv,core-dumps,lost+found";
      baloofilerc.General."exclude filters version" = 9;

      # --- Dolphin ---
      dolphinrc.General.ViewPropsTimestamp = "2025,11,9,21,40,6.029";
      dolphinrc.IconsMode.PreviewSize = 80;
      dolphinrc."KFileDialog Settings"."Places Icons Auto-resize" = false;
      dolphinrc."KFileDialog Settings"."Places Icons Static Size" = 22;

      # --- Activity manager ---
      kactivitymanagerdrc.activities."1029b19e-aca0-4e88-8cb1-476e1816f6e7" = "Default";
      kactivitymanagerdrc.main.currentActivity = "1029b19e-aca0-4e88-8cb1-476e1816f6e7";

      # --- Input ---
      kcminputrc.Mouse.cursorSize = 36;

      # --- KDED modules ---
      kded5rc.Module-browserintegrationreminder.autoload = false;
      kded5rc.Module-device_automounter.autoload = true;

      # --- Global KDE settings ---
      kdeglobals.General.AccentColor = "212,137,53";
      kdeglobals.General.accentColorFromWallpaper = true;
      kdeglobals."KFileDialog Settings"."Allow Expansion" = false;
      kdeglobals."KFileDialog Settings"."Automatically select filename extension" = true;
      kdeglobals."KFileDialog Settings"."Breadcrumb Navigation" = false;
      kdeglobals."KFileDialog Settings"."Decoration position" = 2;
      kdeglobals."KFileDialog Settings"."LocationCombo Completionmode" = 5;
      kdeglobals."KFileDialog Settings"."PathCombo Completionmode" = 5;
      kdeglobals."KFileDialog Settings"."Show Bookmarks" = false;
      kdeglobals."KFileDialog Settings"."Show Full Path" = false;
      kdeglobals."KFileDialog Settings"."Show Inline Previews" = true;
      kdeglobals."KFileDialog Settings"."Show Preview" = false;
      kdeglobals."KFileDialog Settings"."Show Speedbar" = true;
      kdeglobals."KFileDialog Settings"."Show hidden files" = false;
      kdeglobals."KFileDialog Settings"."Sort by" = "Name";
      kdeglobals."KFileDialog Settings"."Sort directories first" = true;
      kdeglobals."KFileDialog Settings"."Sort hidden files last" = false;
      kdeglobals."KFileDialog Settings"."Sort reversed" = false;
      kdeglobals."KFileDialog Settings"."Speedbar Width" = 140;
      kdeglobals."KFileDialog Settings"."View Style" = "DetailTree";
      kdeglobals.WM.activeBackground = "39,44,49";
      kdeglobals.WM.activeBlend = "252,252,252";
      kdeglobals.WM.activeForeground = "252,252,252";
      kdeglobals.WM.inactiveBackground = "32,36,40";
      kdeglobals.WM.inactiveBlend = "161,169,177";
      kdeglobals.WM.inactiveForeground = "161,169,177";

      # --- KRunner ---
      krunnerrc.General.FreeFloating = true;

      # --- Screen locker ---
      kscreenlockerrc.Daemon.LockGrace = 60;
      kscreenlockerrc.Daemon.Timeout = 30;

      # --- KWallet ---
      kwalletrc.Wallet."First Use" = false;

      # --- KWin (tiling UUIDs are machine-specific to aegis) ---
      kwinrc.Desktops.Id_1 = "5d293623-3cbf-48cd-8a3f-8b9290b483f3";
      kwinrc.Desktops.Id_2 = "47455de8-4f16-433e-b8af-c6ad00d9b453";
      kwinrc.Desktops.Id_3 = "586b400c-fa1c-4036-a1cd-1b0f7060f3e2";
      kwinrc.Desktops.Number = 3;
      kwinrc.Desktops.Rows = 1;
      kwinrc.NightColor.Active = true;
      kwinrc.Tiling.padding = 4;
      kwinrc."Tiling/1a225a2e-632f-50d3-aec6-94b1becfdaf3"."[Tiling][47455de8-4f16-433e-b8af-c6ad00d9b453][]" =
        "";
      kwinrc."Tiling/1a225a2e-632f-50d3-aec6-94b1becfdaf3".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/47455de8-4f16-433e-b8af-c6ad00d9b453/0c5d5224-ec55-486a-9567-b67faaa3881c".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/47455de8-4f16-433e-b8af-c6ad00d9b453/9cea2713-9c15-4a67-9014-a5f130fb4488".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/47455de8-4f16-433e-b8af-c6ad00d9b453/c88a7600-d267-4ebe-96a8-789aec3b2385"."[Tiling][586b400c-fa1c-4036-a1cd-1b0f7060f3e2][]" =
        "";
      kwinrc."Tiling/47455de8-4f16-433e-b8af-c6ad00d9b453/c88a7600-d267-4ebe-96a8-789aec3b2385".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/586b400c-fa1c-4036-a1cd-1b0f7060f3e2/0c5d5224-ec55-486a-9567-b67faaa3881c".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/586b400c-fa1c-4036-a1cd-1b0f7060f3e2/9cea2713-9c15-4a67-9014-a5f130fb4488".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/586b400c-fa1c-4036-a1cd-1b0f7060f3e2/c88a7600-d267-4ebe-96a8-789aec3b2385"."[Tiling][5d293623-3cbf-48cd-8a3f-8b9290b483f3][]" =
        "";
      kwinrc."Tiling/586b400c-fa1c-4036-a1cd-1b0f7060f3e2/c88a7600-d267-4ebe-96a8-789aec3b2385".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/5d293623-3cbf-48cd-8a3f-8b9290b483f3/0c5d5224-ec55-486a-9567-b67faaa3881c".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/5d293623-3cbf-48cd-8a3f-8b9290b483f3/9cea2713-9c15-4a67-9014-a5f130fb4488".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/5d293623-3cbf-48cd-8a3f-8b9290b483f3/c88a7600-d267-4ebe-96a8-789aec3b2385".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc."Tiling/92e842d7-5928-5c43-884a-4912e7cc82ed".tiles =
        "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
      kwinrc.Xwayland.Scale = 1.45;
      kwinrc."org.kde.kdecoration2".theme = "Breeze";

      # --- Locale ---
      plasma-localerc.Formats.LANG = "en_US.UTF-8";

      # --- Notification seen-state (app-specific, informational) ---
      plasmanotifyrc."Applications/com.mitchellh.ghostty".Seen = true;
      plasmanotifyrc."Applications/discord".Seen = true;
      plasmanotifyrc."Applications/firefox".Seen = true;
      plasmanotifyrc."Applications/io.github.alainm23.planify".Seen = true;
      plasmanotifyrc."Applications/slack".Seen = true;

      # --- Plasma theme ---
      plasmarc.Theme.name = "Dracula";
      plasmarc.Wallpapers.usersWallpapers = "";

      # --- Spectacle (screenshot tool) ---
      spectaclerc.GuiConfig.captureMode = 0;
      spectaclerc.ImageSave.translatedScreenshotsFolder = "Screenshots";
      spectaclerc.VideoSave.translatedScreencastsFolder = "Screencasts";
    };

    dataFile = {
      "kate/anonymous.katesession"."Kate Plugins".bookmarksplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".cmaketoolsplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".compilerexplorer = false;
      "kate/anonymous.katesession"."Kate Plugins".eslintplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".externaltoolsplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".formatplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katebacktracebrowserplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katebuildplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katecloseexceptplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katecolorpickerplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katectagsplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katefilebrowserplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katefiletreeplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".kategdbplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".kategitblameplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katekonsoleplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".kateprojectplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".katereplicodeplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katesearchplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".katesnippetsplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katesqlplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katesymbolviewerplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katexmlcheckplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".katexmltoolsplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".keyboardmacrosplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".ktexteditorpreviewplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".latexcompletionplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".lspclientplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".openlinkplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".rainbowparens = false;
      "kate/anonymous.katesession"."Kate Plugins".rbqlplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".tabswitcherplugin = true;
      "kate/anonymous.katesession"."Kate Plugins".templateplugin = false;
      "kate/anonymous.katesession"."Kate Plugins".textfilterplugin = true;
      "kate/anonymous.katesession".MainWindow0."Active ViewSpace" = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-H-Splitter = "0,1544,0";
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-0-Bar-0-TvList =
        "kate_private_plugin_katefiletreeplugin,kateproject,kateprojectgit,lspclient_symbol_outline";
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-0-LastSize = 200;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-0-SectSizes = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-0-Splitter = 785;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-1-Bar-0-TvList = "";
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-1-LastSize = 200;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-1-SectSizes = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-1-Splitter = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-2-Bar-0-TvList = "";
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-2-LastSize = 200;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-2-SectSizes = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-2-Splitter = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-3-Bar-0-TvList =
        "output,diagnostics,kate_plugin_katesearch,kateprojectinfo,kate_private_plugin_katekonsoleplugin";
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-3-LastSize = 200;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-3-SectSizes = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-3-Splitter = 1278;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-Style = 2;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-Sidebar-Visible = true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-diagnostics-Position = 3;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-diagnostics-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-diagnostics-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_plugin_katesearch-Position = 3;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_plugin_katesearch-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_plugin_katesearch-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Position =
        0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Visible =
        false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Position =
        3;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Visible =
        false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateproject-Position = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateproject-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateproject-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectgit-Position = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectgit-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectgit-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectinfo-Position = 3;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectinfo-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-kateprojectinfo-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-lspclient_symbol_outline-Position = 0;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-lspclient_symbol_outline-Show-Button-In-Sidebar =
        true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-lspclient_symbol_outline-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-output-Position = 3;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-output-Show-Button-In-Sidebar = true;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-ToolView-output-Visible = false;
      "kate/anonymous.katesession".MainWindow0.Kate-MDI-V-Splitter = "0,785,0";
      "kate/anonymous.katesession"."MainWindow0 Settings".WindowState = 8;
      "kate/anonymous.katesession"."MainWindow0-Splitter 0".Children = "MainWindow0-ViewSpace 0";
      "kate/anonymous.katesession"."MainWindow0-Splitter 0".Orientation = 1;
      "kate/anonymous.katesession"."MainWindow0-Splitter 0".Sizes = 1544;
      "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."Active View" = 0;
      "kate/anonymous.katesession"."MainWindow0-ViewSpace 0".Count = 1;
      "kate/anonymous.katesession"."MainWindow0-ViewSpace 0".Documents = 0;
      "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."View 0" = 0;
      "kate/anonymous.katesession"."Open Documents".Count = 1;
      "kate/anonymous.katesession"."Open MainWindows".Count = 1;
      "kate/anonymous.katesession"."Plugin:kateprojectplugin:".projects = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".BinaryFiles = false;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".CurrentExcludeFilter = "-1";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".CurrentFilter = "-1";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".ExcludeFilters = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".ExpandSearchResults = false;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".Filters = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".FollowSymLink = false;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".HiddenFiles = false;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".MatchCase = false;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".Place = 1;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".Recursive = true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".Replaces = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".Search = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchAsYouTypeAllProjects =
        true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchAsYouTypeCurrentFile =
        true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchAsYouTypeFolder = true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchAsYouTypeOpenFiles = true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchAsYouTypeProject = true;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchDiskFiles = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SearchDiskFiless = "";
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".SizeLimit = 128;
      "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0".UseRegExp = false;
    };
  };
}
